### ISSUE TITLE
REQUEST: New membership for weilaaa

### ISSUE THREAD

**Issue by weilaaa** [karmada-io/community#10]
### GitHub Username

weilaaa

### Requirements

- [X] I have reviewed the [community membership guidelines](https://github.com/karmada-io/community/blob/main/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [Karmada mailing list](https://groups.google.com/forum/#!forum/karmada)
- [x] I am actively contributing to 1 or more Karmada subprojects
- [ ] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [ ] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [ ] I have verified that my sponsors are from different member companies
- [ ] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Karmada GitHub organizations

### Sponsor 1

@RainbowMango

### Sponsor 2

@pigletfly

### List of contributions to the Karmada project

List of contributions to the Karmada project
PRs authored:

https://github.com/karmada-io/karmada/pull/582
https://github.com/karmada-io/karmada/pull/586
https://github.com/karmada-io/karmada/pull/1224
https://github.com/karmada-io/karmada/pull/2311

**Comment by weilaaa** [comment]
@kevin-wangzefeng RainbowMango

**Comment by RainbowMango** [comment]
+1
Thanks @weilaaa for all your contribution. 
I remember that @weilaaa started contributing to this project at a very early stage.

**Comment by kevin-wangzefeng** [comment]
Invitation sent, please visit https://github.com/karmada-io to confirm and join
