### ISSUE TITLE
REQUEST: New membership for jwcesign

### ISSUE THREAD

**Issue by jwcesign** [karmada-io/community#12]
### GitHub Username

@jwcesign

### Requirements

- [X] I have reviewed the [community membership guidelines](https://github.com/karmada-io/community/blob/main/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [Karmada mailing list](https://groups.google.com/forum/#!forum/karmada)
- [X] I am actively contributing to 1 or more Karmada subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Karmada GitHub organizations

### Sponsor 1

@RainbowMango

### Sponsor 2

@lonelyCZ 

### List of contributions to the Karmada project

My PR:
* https://github.com/karmada-io/karmada/pull/2536
* https://github.com/karmada-io/karmada/pull/2539
* https://github.com/karmada-io/karmada/pull/2547
* https://github.com/karmada-io/karmada/pull/2548
* https://github.com/karmada-io/karmada/pull/2551
* https://github.com/karmada-io/karmada/pull/2560
* https://github.com/karmada-io/karmada/pull/2563

Review PR:
* https://github.com/karmada-io/karmada/pull/2596
* https://github.com/karmada-io/karmada/pull/2610
* https://github.com/karmada-io/karmada/pull/2645

Issues responsed:
* https://github.com/karmada-io/karmada/issues/2571

**Comment by jwcesign** [comment]
cc @lonelyCZ @RainbowMango

**Comment by RainbowMango** [comment]
+1

**Comment by lonelyCZ** [comment]
+1

**Comment by kevin-wangzefeng** [comment]
Invitation sent, please visit https://github.com/karmada-io to confirm and join
