### ISSUE TITLE
REQUEST: New membership for helen-frank

### ISSUE THREAD

**Issue by helen-frank** [karmada-io/community#14]
### GitHub Username

helen-frank

### Requirements

- [X] I have reviewed the [community membership guidelines](https://github.com/karmada-io/community/blob/main/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [Karmada mailing list](https://groups.google.com/forum/#!forum/karmada)
- [X] I am actively contributing to 1 or more Karmada subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Karmada GitHub organizations

### Sponsor 1

@carlory

### Sponsor 2

@lonelyCZ

### List of contributions to the Karmada project

[PR job](https://github.com/karmada-io/karmada/pulls?q=is%3Apr+author%3Ahelen-frank+is%3Aclosed)
[REVIEW job](https://github.com/karmada-io/karmada/pull/2668)

**Comment by carlory** [comment]
+1
Thanks @helen-frank  for all your contributions!

/cc @RainbowMango

**Comment by lonelyCZ** [comment]
+1

**Comment by RainbowMango** [comment]
Thanks @helen-frank 
/assign @kevin-wangzefeng

**Comment by kevin-wangzefeng** [comment]
Invitation sent, please visit https://github.com/karmada-io to confirm and join

**Comment by helen-frank** [comment]
@carlory @lonelyCZ @RainbowMango @kevin-wangzefeng Thanks for this.

**Comment by RainbowMango** [comment]
/close
welcome @helen-frank .
