### ISSUE TITLE
REQUEST: New membership for fsl

### ISSUE THREAD

**Issue by fengshunli** [karmada-io/community#22]
### GitHub Username

@fengshunli

### Requirements

- [X] I have reviewed the [community membership guidelines](https://github.com/karmada-io/community/blob/main/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [Karmada mailing list](https://groups.google.com/forum/#!forum/karmada)
- [X] I am actively contributing to 1 or more Karmada subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Karmada GitHub organizations

### Sponsor 1

@RainbowMango

### Sponsor 2

@Garrybest 

### List of contributions to the Karmada project

https://github.com/karmada-io/karmada/pull/3045
https://github.com/karmada-io/website/pull/292
https://github.com/karmada-io/website/pull/293
https://github.com/karmada-io/karmada/pull/3048

**Comment by RainbowMango** [comment]
Hi @fengshunli I'm glad to be your sponsor but according to [requirements](https://github.com/karmada-io/community/blob/main/community-membership.md#requirements):
> Sponsors must be from multiple member companies to demonstrate integration across community.

You still need to find another sponsor who is not from Huawei. (Both me and @XiShanYongYe-Chang are from Huawei).

**Comment by fengshunli** [comment]
> Hi @fengshunli I'm glad to be your sponsor but according to [requirements](https://github.com/karmada-io/community/blob/main/community-membership.md#requirements):
> 
> > Sponsors must be from multiple member companies to demonstrate integration across community.
> 
> You still need to find another sponsor who is not from Huawei. (Both me and @XiShanYongYe-Chang are from Huawei).

@Garrybest can you

**Comment by Garrybest** [comment]
Thanks for your contribution! 🎉 👍

I'd like to sponsor @fengshunli

**Comment by fengshunli** [comment]
@RainbowMango sponsors are enough

**Comment by RainbowMango** [comment]
OK.
/assign @kevin-wangzefeng 
Kevin will send you the invitation later.

**Comment by fengshunli** [comment]
please agree @kevin-wangzefeng

**Comment by kevin-wangzefeng** [comment]
Invitation sent, please visit https://github.com/karmada-io to confirm and join, thanks.

**Comment by RainbowMango** [comment]
/close
Welcome @fengshunli to the Karmada community!
