### ISSUE TITLE
REQUEST: New membership for xigang

### ISSUE THREAD

**Issue by xigang** [karmada-io/community#24]
### GitHub Username

@xigang

### Requirements

- [X] I have reviewed the [community membership guidelines](https://github.com/karmada-io/community/blob/main/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [Karmada mailing list](https://groups.google.com/forum/#!forum/karmada)
- [X] I am actively contributing to 1 or more Karmada subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Karmada GitHub organizations

### Sponsor 1

@RainbowMango

### Sponsor 2

@XiShanYongYe-Chang

### Sponsor 3
@Garrybest

### List of contributions to the Karmada project

List of contributions to the Karmada project
PRs authored: 

- https://github.com/karmada-io/karmada/pull/3288
-  https://github.com/karmada-io/karmada/pull/3316

Issues responsed:

- https://github.com/karmada-io/karmada/pull/3147
- https://github.com/karmada-io/karmada/issues/3275
- https://github.com/karmada-io/karmada/issues/3313

**Comment by XiShanYongYe-Chang** [comment]
Hi @xigang I'm glad to be your sponsor but according to [requirements](https://github.com/karmada-io/community/blob/main/community-membership.md#requirements):

> Sponsors must be from multiple member companies to demonstrate integration across community.

In view of the above, you still need to find another sponsor who is not from Huawei. (@RainbowMango, @Poor12, and I are all from Huawei).

**Comment by RainbowMango** [comment]
Hi @xigang 
Thanks for all your contributions to the community. I'm glad to sponsor you, but [there is a requirement](https://github.com/karmada-io/community/blob/main/community-membership.md#requirements) shows that
> Sponsors must be from multiple member companies to demonstrate integration across community.

So, you might need to find another sponsor who has close interactions with you.

You can get all the reviewers(sponsors) from [this table](https://github.com/karmada-io/community/blob/main/REVIEWERS.md).

**Comment by xigang** [comment]
> Hi @xigang I'm glad to be your sponsor but according to [requirements](https://github.com/karmada-io/community/blob/main/community-membership.md#requirements):
> 
> > Sponsors must be from multiple member companies to demonstrate integration across community.
> 
> You still need to find another sponsor who is not from Huawei. (@RainbowMango, @Poor12, and I are all from Huawei).
/assign Garrybest

**Comment by Garrybest** [comment]
Congratulations! Welcome to karmada! @xigang
/lgtm

**Comment by RainbowMango** [comment]
+1
Welcome~ Thanks for your contributions.

/assign @kevin-wangzefeng

**Comment by RainbowMango** [comment]
Thanks Kevin.
/close
