### ISSUE TITLE
REQUEST: New membership for whitewindmills

### ISSUE THREAD

**Issue by whitewindmills** [karmada-io/community#25]
### GitHub Username

@whitewindmills

### Requirements

- [X] I have reviewed the [community membership guidelines](https://github.com/karmada-io/community/blob/main/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [Karmada mailing list](https://groups.google.com/forum/#!forum/karmada)
- [X] I am actively contributing to 1 or more Karmada subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Karmada GitHub organizations

### Sponsor 1

@RainbowMango

### Sponsor 2

@chaunceyjiang

### List of contributions to the Karmada project

PRs authored:
* https://github.com/karmada-io/karmada/pull/3052
* https://github.com/karmada-io/karmada/pull/3201
* https://github.com/karmada-io/karmada/pull/3229
* https://github.com/karmada-io/karmada/pull/3232
* https://github.com/karmada-io/karmada/pull/3274
* https://github.com/karmada-io/karmada/pull/3278
* https://github.com/karmada-io/karmada/pull/2940
* https://github.com/karmada-io/karmada/pull/2915
* https://github.com/karmada-io/karmada/pull/3213
* https://github.com/karmada-io/karmada/pull/3214
* https://github.com/karmada-io/karmada/pull/3215
* https://github.com/karmada-io/karmada/pull/3222
* https://github.com/karmada-io/website/pull/316
* https://github.com/karmada-io/website/pull/329

Issues responsed:
* https://github.com/karmada-io/karmada/issues/3231
* https://github.com/karmada-io/karmada/issues/2697

**Comment by chaunceyjiang** [comment]
+1
👏👋
Welcome~

**Comment by RainbowMango** [comment]
+1
Thanks @whitewindmills for all your contributions.

/assign @kevin-wangzefeng

**Comment by RainbowMango** [comment]
Thanks Kevin.
/close
