### ISSUE TITLE
REQUEST: New membership for yanfeng1992

### ISSUE THREAD

**Issue by yanfeng1992** [karmada-io/community#26]
### GitHub Username

@yanfeng1992

### Requirements

- [X] I have reviewed the [community membership guidelines](https://github.com/karmada-io/community/blob/main/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [Karmada mailing list](https://groups.google.com/forum/#!forum/karmada)
- [X] I am actively contributing to 1 or more Karmada subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Karmada GitHub organizations

### Sponsor 1

@XiShanYongYe-Chang

### Sponsor 2

@lonelyCZ

### List of contributions to the Karmada project

PRs authored:
- https://github.com/karmada-io/karmada/pull/3221
- https://github.com/karmada-io/karmada/pull/3010
- https://github.com/karmada-io/karmada/pull/2911
- https://github.com/karmada-io/karmada/pull/2949
- https://github.com/karmada-io/karmada/pull/3019
- https://github.com/karmada-io/karmada/pull/3018
- https://github.com/karmada-io/karmada/pull/3016
- https://github.com/karmada-io/karmada/pull/3044
Issues responsed:
- https://github.com/karmada-io/karmada/issues/3113

**Comment by lonelyCZ** [comment]
+1

Welcome! Thanks for your contributes.

**Comment by XiShanYongYe-Chang** [comment]
+1
 Welcome! Thanks @yanfeng1992  for all your contributions.

/assign @kevin-wangzefeng

**Comment by yanfeng1992** [comment]
cc @kevin-wangzefeng

**Comment by kevin-wangzefeng** [comment]
Invitation sent, please visit https://github.com/karmada-io to confirm and join.

**Comment by yanfeng1992** [comment]
Thank you all, the invitation has been confirmed

**Comment by RainbowMango** [comment]
Welcome @yanfeng1992.
/close
