### ISSUE TITLE
REQUEST: New repo for building multicluster-cloud-provider

### ISSUE THREAD

**Issue by XiShanYongYe-Chang** [karmada-io/community#29]
## Backgroud

To enable Karmada to run on the public cloud platform and flexibly use and manage other basic resources and services on the cloud, cloud providers need to implement their own adapters. However, in the implementation process, some works are the same for each cloud provider.

Learn from the experience of Kubernetes Cloud Controller Manager (CCM): https://github.com/kubernetes/cloud-provider. Karmada can also provide a public repository that provides interfaces for using and managing basic resources and services on the public cloud. Cloud providers only need to implement these interfaces to provide users with their own adapters.

## Repository Name

*multicluster-cloud-provider*

multicluster-cloud-provider defines the shared interfaces which Karmada cloud providers implement. These interfaces allow various controllers to integrate with any cloud provider in a pluggable fashion.

**Comment by kevin-wangzefeng** [comment]
Thanks for proposing this, cloud provider support is definitely important part of the community.
Do you have further details about the idea? E.g. which components are included or is it dedicated for either mci, dns, etc.

**Comment by XiShanYongYe-Chang** [comment]
My idea is that the `multicluster-cloud-provider` and the various providers' adapters will act as an intermediary for Karmada to communicate with the cloud provider, and as a whole, they will allow Karmada to directly leverage the underlying resources and services of the cloud provider. Implements load balancing, network routing, DNS resolution, persistent volumes and so on.

For the current plan, we hope that `multicluster-cloud-provider` provides the `MultiClusterIngress` capability first. When users perform operations on `MultiClusterIngress` resources, the loadbalancer service on the cloud provider can be synchronized.

Next, we want `multicluster-cloud-provider` to provide the `MultiClusterService` capability, which is also related to the loadbalancer service on the cloud provider.

In the future, we may plan network routing, DNS resolution, and persistent volume capabilities in `multicluster-cloud-provider`.

Therefore, the `multicluster-cloud-provider` repo as a framework, provides only shared interfaces and the control of related resources (such as MCI). The adapters repo of each cloud provider needs to be processed separately. During the implementation, we only need to import `multicluster-cloud-provider`.

**Comment by RainbowMango** [comment]
We talked about the provider issue at [25/04/2023 community meeting](https://docs.google.com/document/d/1y6YLVC-v7cmVAdbjedoyR5WL0-q45DBRXTvz5_I7bkA/edit?pli=1#heading=h.z8zu4fcowntv), I agree to have a repo holds the common components. 

Given in the near future we might need `MCI` provider and `MCS` provider, it makes sense to have a common repo like `multicluster-cloud-provider`, the components in it could be:
- mci-cloud-provider
- mcs-cloud-provider
- etc.

**Comment by kevin-wangzefeng** [comment]
Agree with `mci-cloud-provider` and `mcs-cloud-provider`.
I'm going to create the repos accordingly.

**Comment by XiShanYongYe-Chang** [comment]
The repo https://github.com/karmada-io/multicluster-cloud-provider/ has been created.
Thanks~ @kevin-wangzefeng @RainbowMango 
/close
