### ISSUE TITLE
REQUEST: New membership for windsonsea

### ISSUE THREAD

**Issue by windsonsea** [karmada-io/community#3]
### GitHub Username

@windsonsea

### Organization you are requesting membership in

Karmada docs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://github.com/karmada-io/community/blob/main/community-membership.md)
- [X] I have read the [Contributor Guide](https://github.com/karmada-io/community/blob/main/contributors/guide/README.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [Karmada mailing list](https://groups.google.com/g/karmada)
- [X] I am actively contributing to 1 or more Karmada subprojects

### Sponsor 1

@kerthcet 

### Sponsor 2

@RainbowMango 

### Sponsor 3

@Arhell 

### List of contributions to the Karmada project

- PRs authored: [#85](https://github.com/karmada-io/website/pull/85), [#86](https://github.com/karmada-io/website/pull/86), [#98](https://github.com/karmada-io/website/pull/98), [#99](https://github.com/karmada-io/website/pull/99), [#2040](https://github.com/karmada-io/karmada/pull/2040), [#105](https://github.com/karmada-io/website/pull/105), [#87](https://github.com/karmada-io/website/pull/87), [#107](https://github.com/karmada-io/website/pull/107)
- Issues responded to: [#73](https://github.com/karmada-io/website/issues/73) and more that I cannot find now

**Comment by kerthcet** [comment]
+1, document contributions are quite valuable to new karmada folks, hoping to see more contributions from @windsonsea

**Comment by rgrupesh** [comment]
+1.

**Comment by RainbowMango** [comment]
+1
/assign @kevin-wangzefeng

**Comment by kevin-wangzefeng** [comment]
Invitation sent, you shall be receiving an email shortly. You can also visit [@karmada-io](https://github.com/karmada-io) to accept the invitation.

**Comment by windsonsea** [comment]
Thanks 😄

**Comment by kevin-wangzefeng** [comment]
Welcome onboard, looking forward to more of your contributions.
