### ISSUE TITLE
Update Meeting time of English biweekly

### ISSUE THREAD

**Issue by liangyuanpeng** [karmada-io/community#30]
This issue is tracing for update README for meeting time of English biweekly, the first time is `16/05/2023 @ 8am PT` , check https://github.com/karmada-io/karmada/issues/1560#issuecomment-1549073551

README can be update after formal confirmation.

**Comment by RainbowMango** [comment]
Thanks for the reminder. I have updated the README for `karmada` repo at #3471.

Would you like to send a PR for the community repo?
We can fix (close) #1560 as well by this PR.
