### ISSUE TITLE
REQUEST: New membership for learner0810

### ISSUE THREAD

**Issue by learner0810** [karmada-io/community#32]
### GitHub Username

@learner0810

### Requirements

- [X] I have reviewed the [community membership guidelines](https://github.com/karmada-io/community/blob/main/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [Karmada mailing list](https://groups.google.com/forum/#!forum/karmada)
- [X] I am actively contributing to 1 or more Karmada subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Karmada GitHub organizations

### Sponsor 1

@RainbowMango

### Sponsor 2

@calvin0327

### List of contributions to the Karmada project

PRs authored:

- https://github.com/karmada-io/karmada/pull/3530
- https://github.com/karmada-io/karmada/pull/1900
- https://github.com/karmada-io/karmada/pull/911
- https://github.com/karmada-io/karmada/pull/908
- https://github.com/karmada-io/karmada/pull/904
- https://github.com/karmada-io/karmada/pull/881
- https://github.com/karmada-io/karmada/pull/877
- https://github.com/karmada-io/karmada/pull/864
- https://github.com/karmada-io/karmada/pull/787
- https://github.com/karmada-io/karmada/pull/785

Issues responsed:

- https://github.com/karmada-io/karmada/issues/3588
- https://github.com/karmada-io/karmada/issues/906
- https://github.com/karmada-io/karmada/issues/906
- https://github.com/karmada-io/karmada/issues/878
- https://github.com/karmada-io/karmada/issues/861

**Comment by calvin0327** [comment]
thanks for your contribution.
 +1

**Comment by RainbowMango** [comment]
+1
/assign @kevin-wangzefeng 
to send the invitation.

**Comment by learner0810** [comment]
cc @kevin-wangzefeng

**Comment by kevin-wangzefeng** [comment]
Invitation sent, you will be receiving an email shortly.

**Comment by learner0810** [comment]
Thank you all, the invitation has been confirmed
