### ISSUE TITLE
REQUEST: New membership for yike21

### ISSUE THREAD

**Issue by yike21** [karmada-io/community#33]
### GitHub Username

@yike21

### Requirements

- [X] I have reviewed the [community membership guidelines](https://github.com/karmada-io/community/blob/main/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [Karmada mailing list](https://groups.google.com/forum/#!forum/karmada)
- [X] I am actively contributing to 1 or more Karmada subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Karmada GitHub organizations

### Sponsor 1

@Poor12

### Sponsor 2

@chaunceyjiang

### List of contributions to the Karmada project

PRs authored:
 *  https://github.com/karmada-io/karmada/pull/3629
 * https://github.com/karmada-io/karmada/pull/3499
 * https://github.com/karmada-io/karmada/pull/3498
 * https://github.com/karmada-io/karmada/pull/3488
 * https://github.com/karmada-io/karmada/pull/3487
 * https://github.com/karmada-io/karmada/pull/3486
 * https://github.com/karmada-io/karmada/pull/3485
 * https://github.com/karmada-io/karmada/pull/3484
 * https://github.com/karmada-io/karmada/pull/3482
 * https://github.com/karmada-io/karmada/pull/3481
 * https://github.com/karmada-io/karmada/pull/3462
 * https://github.com/karmada-io/karmada/pull/3438
 * https://github.com/karmada-io/karmada/pull/3412
 * https://github.com/karmada-io/karmada/pull/3392
 * https://github.com/karmada-io/karmada/pull/3368
 * https://github.com/karmada-io/karmada/pull/3366
 * https://github.com/karmada-io/karmada/pull/3358
 * https://github.com/karmada-io/karmada/pull/3352
 * https://github.com/karmada-io/karmada/pull/3339
 * https://github.com/karmada-io/karmada/pull/3337
 * https://github.com/karmada-io/website/pull/360
 * https://github.com/karmada-io/website/pull/353

Issues authored:
 * https://github.com/karmada-io/karmada/issues/3564
 * https://github.com/karmada-io/karmada/issues/3551
 * https://github.com/karmada-io/karmada/issues/3401
 * https://github.com/karmada-io/karmada/issues/3331

Issues responsed:
 * https://github.com/karmada-io/karmada/issues/3628
 * https://github.com/karmada-io/karmada/issues/3624
 * https://github.com/karmada-io/karmada/issues/3592
 * https://github.com/karmada-io/website/issues/347
 * https://github.com/karmada-io/website/issues/343

**Comment by Poor12** [comment]
+1

**Comment by chaunceyjiang** [comment]
+1

**Comment by RainbowMango** [comment]
Welcome @yike21 
Thanks for all the contributions.

/assign @kevin-wangzefeng

**Comment by yike21** [comment]
cc @kevin-wangzefeng

**Comment by RainbowMango** [comment]
Hi @yike21 
Kevin is not in the office these days. He will send you an invitation when he comes back. Please be patient and wait for a while.

**Comment by yike21** [comment]
> Hi @yike21 Kevin is not in the office these days. He will send you an invitation when he comes back. Please be patient and wait for a while.

Ok, thanks a lot!

**Comment by yike21** [comment]
Thank you all, the invitation has been confirmed

**Comment by RainbowMango** [comment]
Then we can close it now.
/close

**Comment by kevin-wangzefeng** [comment]
Congrats and welcome onboard, looking forward to more of your contributions.
