### ISSUE TITLE
REQUEST: New membership for yanggangtony

### ISSUE THREAD

**Issue by yanggangtony** [karmada-io/community#34]
### GitHub Username

@yanggangtony

### Requirements

- [X] I have reviewed the [community membership guidelines](https://github.com/karmada-io/community/blob/main/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [Karmada mailing list](https://groups.google.com/forum/#!forum/karmada)
- [X] I am actively contributing to 1 or more Karmada subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Karmada GitHub organizations

### Sponsor 1

@RainbowMango

### Sponsor 2

@chaunceyjiang

### List of contributions to the Karmada project

Hi, karmada community.
I recently have contributed pr in  karmada.

karmada repo pr: 
[karmada](https://github.com/karmada-io/karmada/pulls?q=is%3Apr+author%3Ayanggangtony+is%3Aclosed)

karmada-website repo pr: 
[karmada-website](https://github.com/karmada-io/website/pulls?q=is%3Apr+author%3Ayanggangtony+is%3Aclosed)

karmada-multi-cluster-ingress-nginx repo pr:
[karmada-multi-cluster-ingress-nginx](https://github.com/karmada-io/multi-cluster-ingress-nginx/pulls/yanggangtony)

----------------------------------------------------------------------------------------------------------
And I also a k8s developer at @DaoCloud Shanghai.  
I like k8s and its downstream projects a lot.

I want to do more work for karmada community in the future.
Thanks.

**Comment by yanggangtony** [comment]
/assign @RainbowMango  
/assign @chaunceyjiang 
Please take a look , thanks.

**Comment by RainbowMango** [comment]
+1 
Thanks for all your contributions to the community!

**Comment by chaunceyjiang** [comment]
+1

Welcome!

**Comment by yanggangtony** [comment]
Thanks a lot.
I got the email notification.

**Comment by kevin-wangzefeng** [comment]
Congrats and welcome onboard, looking forward to more of your contributions.
