### ISSUE TITLE
Request: Archive karmada-operator repo

### ISSUE THREAD

**Issue by RainbowMango** [karmada-io/community#38]
## Backgroud

The `karmada-io/karmada-operator` repo was created for building `karmada-operator` functionalities.

But due to `karmada-operator` heavily depending on components/utils from `karmada-io/karmada`, we decided to move the effort to 
karmada repo, that is [pkg/operator](https://github.com/karmada-io/karmada/tree/master/operator).

## Repository to archive

`karmada-io/karmada-operator`

## Additional context for the request

We should try to avoid confusion like https://github.com/karmada-io/karmada-operator/issues/12.

Given we moved the effort to the karmada repo at a very early stage, no one is using or relying on this repo, so we can delete the repo directly.

**Comment by kevin-wangzefeng** [comment]
The repo https://github.com/karmada-io/karmada-operator is now archived
