### ISSUE TITLE
REQUEST: New membership for JadeFlute0127

### ISSUE THREAD

**Issue by JadeFlute0127** [karmada-io/community#41]
### GitHub Username

@JadeFlute0127

### Requirements

- [X] I have reviewed the [community membership guidelines](https://github.com/karmada-io/community/blob/main/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [Karmada mailing list](https://groups.google.com/forum/#!forum/karmada)
- [X] I am actively contributing to 1 or more Karmada subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Karmada GitHub organizations

### Sponsor 1

@jwcesign

### Sponsor 2

@RainbowMango

### List of contributions to the Karmada project

List of contributions to the Karmada project
PRs authored: 
https://github.com/karmada-io/playground/pull/2
https://github.com/karmada-io/playground/pull/3
https://github.com/karmada-io/playground/pull/5

**Comment by jwcesign** [comment]
+1
@JadeFlute0127 made a great contribution to the playgroup, allowing users to try out the core scenarios of Karmada.

/cc @RainbowMango @kevin-wangzefeng

**Comment by RainbowMango** [comment]
I'd love to sponsor you, but as per the [community membership](https://github.com/karmada-io/community/blob/main/community-membership.md#requirements):

> Sponsors must be from multiple member companies to demonstrate integration across community.

Both I and @jwcesign are from Huawei, so you might need to find another sponsor who has close interactions with you to continue the process.

**Comment by JadeFlute0127** [comment]
> I'd love to sponsor you, but as per the [community membership](https://github.com/karmada-io/community/blob/main/community-membership.md#requirements):
> 
> > Sponsors must be from multiple member companies to demonstrate integration across community.
> 
> Both I and @jwcesign are from Huawei, so you might need to find another sponsor who has close interactions with you to continue the process.

Thanks for your reminder, I will continue to look for a compliant sponsor. I am passionate about maintaining the playground repository and will continue to add Karmada scenario examples through third parties such as killercoda.  :smiley:

**Comment by RainbowMango** [comment]
+1
Sorry I missed this.
/assign @kevin-wangzefeng

**Comment by kevin-wangzefeng** [comment]
Thank you for your contributions, invitation sent, please visit [@karmada-io](https://github.com/karmada-io) to accept the invitation.
