### ISSUE TITLE
REQUEST: New membership for justedennnnn

### ISSUE THREAD

**Issue by justedennnnn** [karmada-io/community#46]
### GitHub Username

@justedennnnn

### Requirements

- [X] I have reviewed the [community membership guidelines](https://github.com/karmada-io/community/blob/main/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [Karmada mailing list](https://groups.google.com/forum/#!forum/karmada)
- [X] I am actively contributing to 1 or more Karmada subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Karmada GitHub organizations

### Sponsor 1

@SAMZONG

### Sponsor 2

@RainbowMango 

### List of contributions to the Karmada project

PR authored：
1. https://github.com/karmada-io/website/pull/405
2. https://github.com/karmada-io/website/pull/401
3. https://github.com/karmada-io/website/pull/371
4. https://github.com/karmada-io/website/pull/162

**Comment by SAMZONG** [comment]
Welcome to the Karmada family, U have my full support.

**Comment by justedennnnn** [comment]
> Welcome to the Karmada family, U have my full support.

Thanks a lot.

**Comment by windsonsea** [comment]
+1
Welcome. Look forward to your more contributions.

**Comment by justedennnnn** [comment]
> 

Thanks .

**Comment by RainbowMango** [comment]
+1
/assign @kevin-wangzefeng

**Comment by justedennnnn** [comment]
cc @kevin-wangzefeng

**Comment by kevin-wangzefeng** [comment]
Invitation sent, you can visit https://github.com/karmada-io to accept and join.

**Comment by justedennnnn** [comment]
> Invitation sent, you can visit https://github.com/karmada-io to accept and join.

Thanks a lot.
I got the email notification.
