### ISSUE TITLE
REQUEST: New membership for samzong.lu (Chinese nickname 船长)

### ISSUE THREAD

**Issue by SAMZONG** [karmada-io/community#5]
GitHub Username
@samzong

Organization you are requesting membership in
Karmada website
Karmada docs

Requirements
 I have reviewed the [community membership guidelines](https://github.com/karmada-io/community/blob/main/community-membership.md)
 I have read the [Contributor Guide](https://github.com/karmada-io/community/blob/main/contributors/guide/README.md)
 I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
 I have subscribed to the [Karmada mailing list](https://groups.google.com/g/karmada)
 I am actively contributing to 1 or more Karmada subprojects

Sponsor 1
@RainbowMango

Sponsor 2
@kerthcet

Sponsor 3
@Arhell

List of contributions to the Karmada project
PRs authored: 
- https://github.com/karmada-io/website/pull/89

Issues authored:
- https://github.com/karmada-io/community/issues/2
- https://github.com/karmada-io/karmada/issues/1976

**Comment by Arhell** [comment]
+1

**Comment by SAMZONG** [comment]
qiu qiu ~

**Comment by RainbowMango** [comment]
+1

@kevin-wangzefeng 
@SAMZONG is now building a platform based on Karmada to serve customers and gave bunches of feedback as well as improvement proposals to the community. 

/assign @kevin-wangzefeng

**Comment by kevin-wangzefeng** [comment]
Invitation sent, you shall be receiving an email shortly. You can also visit https://github.com/karmada-io to accept the invitation.

**Comment by SAMZONG** [comment]
@kevin-wangzefeng @RainbowMango Thanks for this.

**Comment by RainbowMango** [comment]
/close
Seems all set now.
