### ISSUE TITLE
[WIP] REQUEST: New membership for Vacant2333

### ISSUE THREAD

**Issue by Vacant2333** [karmada-io/community#52]
### GitHub Username

@Vacant2333

### Requirements

- [X] I have reviewed the [community membership guidelines](https://github.com/karmada-io/community/blob/main/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [Karmada mailing list](https://groups.google.com/forum/#!forum/karmada)
- [X] I am actively contributing to 1 or more Karmada subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Karmada GitHub organizations

### Sponsor 1

@XiShanYongYe-Chang

### Sponsor 2

@carlory 

### List of contributions to the Karmada project

PRs authored:
- https://github.com/karmada-io/karmada/pull/3957
- https://github.com/karmada-io/karmada/pull/3944
- https://github.com/karmada-io/karmada/pull/3928
- https://github.com/karmada-io/karmada/pull/3796
- https://github.com/karmada-io/karmada/pull/3618
- https://github.com/karmada-io/karmada/pull/3563
- https://github.com/karmada-io/karmada/pull/3953
- https://github.com/karmada-io/karmada/pull/3802

Isseus authored:
- https://github.com/karmada-io/karmada/issues/3560
- https://github.com/karmada-io/karmada/issues/3935
- https://github.com/karmada-io/karmada/issues/3956
- https://github.com/karmada-io/karmada/issues/3963

PRs responded:
- https://github.com/karmada-io/karmada/pull/3832
- https://github.com/karmada-io/karmada/pull/3937
- https://github.com/karmada-io/karmada/pull/3838

Issues responded:
- https://github.com/karmada-io/karmada/issues/3728
- https://github.com/karmada-io/karmada/issues/3916
- https://github.com/karmada-io/karmada/issues/3685

**Comment by carlory** [comment]
+1 welcome 👍

**Comment by XiShanYongYe-Chang** [comment]
Welcome @Vacant2333 
Thanks for all the contributions. 👍

**Comment by RainbowMango** [comment]
Glad to have you @Vacant2333 .

/assign @kevin-wangzefeng

**Comment by kevin-wangzefeng** [comment]
Invitation sent, you can visit https://github.com/karmada-io to accept and join.

**Comment by Vacant2333** [comment]
thanks！

**Comment by RainbowMango** [comment]
/close
Welcome @Vacant2333.
