### ISSUE TITLE
REQUEST: New membership for zhzhuang-zju

### ISSUE THREAD

**Issue by zhzhuang-zju** [karmada-io/community#57]
### GitHub Username

@zhzhuang-zju

### Requirements

- [X] I have reviewed the [community membership guidelines](https://github.com/karmada-io/community/blob/main/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [Karmada mailing list](https://groups.google.com/forum/#!forum/karmada)
- [X] I am actively contributing to 1 or more Karmada subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Karmada GitHub organizations

### Sponsor 1

@whitewindmills

### Sponsor 2

@Garrybest

### Sponsor 3

@carlory

### Sponsor 4

@yike21

### List of contributions to the Karmada project

List of contributions to the Karmada project
- https://github.com/karmada-io/karmada/pull/4123
- https://github.com/karmada-io/karmada/pull/4144
- https://github.com/karmada-io/karmada/pull/4147
- https://github.com/karmada-io/karmada/pull/4198
- https://github.com/karmada-io/karmada/pull/4223
- https://github.com/karmada-io/karmada/pull/4237
- https://github.com/karmada-io/community/pull/54

Full PR list can be found at https://github.com/karmada-io/karmada/pulls?q=is%3Apr+author%3Azhzhuang-zju+is%3Aclosed

**Comment by RainbowMango** [comment]
>  I have verified that my sponsors are from different member companies

@RainbowMango and @XiShanYongYe-Chang are from the same company. You might need to find another sponsor.

**Comment by zhzhuang-zju** [comment]
> > I have verified that my sponsors are from different member companies
> 
> @RainbowMango and @XiShanYongYe-Chang are from the same company. You might need to find another sponsor.

Thanks for reminding me!

**Comment by whitewindmills** [comment]
+1
welcome

**Comment by carlory** [comment]
+1

**Comment by yike21** [comment]
+1
welcome

**Comment by kevin-wangzefeng** [comment]
Invitation sent. You will be receiving an email shortly. You can also visit https://github.com/karmada-io to accept the invitation.

**Comment by zhzhuang-zju** [comment]
Thank you very much, I have accepted and joined~
