### ISSUE TITLE
REQUEST: New membership for zhy76

### ISSUE THREAD

**Issue by zhy76** [karmada-io/community#59]
### GitHub Username

@zhy76

### Requirements

- [X] I have reviewed the [community membership guidelines](https://github.com/karmada-io/community/blob/main/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [Karmada mailing list](https://groups.google.com/forum/#!forum/karmada)
- [X] I am actively contributing to 1 or more Karmada subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Karmada GitHub organizations

### Sponsor 1

@jwcesign

### Sponsor 2

@chaunceyjiang

### List of contributions to the Karmada project

PRs authored: 
- https://github.com/karmada-io/karmada/pull/4100
- https://github.com/karmada-io/karmada/pull/3972
- https://github.com/karmada-io/karmada/pull/3937
- https://github.com/karmada-io/karmada/pull/3839
- https://github.com/karmada-io/karmada/pull/3801
- https://github.com/karmada-io/website/pull/458
- https://github.com/karmada-io/karmada/pull/4204
- https://github.com/karmada-io/karmada/pull/4135

Isseus authored: 
- https://github.com/karmada-io/karmada/issues/4036

PRs responded: 
- https://github.com/karmada-io/karmada/pull/3838

Issues responded:
- https://github.com/karmada-io/karmada/issues/2862
- https://github.com/karmada-io/karmada/issues/3731
- https://github.com/karmada-io/karmada/issues/3842
- https://github.com/karmada-io/karmada/issues/3946
- https://github.com/karmada-io/karmada/issues/3916

**Comment by chaunceyjiang** [comment]
+1 ❤️

**Comment by kevin-wangzefeng** [comment]
Thanks for your contributions
I've sent the invitation, you can visit https://github.com/karmada-io to accept the invitation.

**Comment by RainbowMango** [comment]
/close
as @zhy76 is on the [member list](https://github.com/orgs/karmada-io/people) now.
