### ISSUE TITLE
REQUEST: Organization DaoCloud that provides commercial support to Karmada New Commercial Support 

### ISSUE THREAD

**Issue by wawa0210** [karmada-io/community#60]
### Org or company name

[DaoCloud](https://www.daocloud.io/)

### Org or company description

DaoCloud is an innovation leader in the cloud native field. With the competitive expertise of its proprietary intellectual property rights, DaoCloud is committed to creating an open Cloud OS which enables enterprises to easily carry out digital transformation.

### Org or company Website

https://docs.daocloud.io/kairship/intro/index.html

### Org or company logo

![image](https://github.com/karmada-io/community/assets/7907809/af4ef1a8-1ca6-4576-aace-a27f12557875)

### Contact me

info@daocloud.io

**Comment by RainbowMango** [comment]
/close

The partnership can be found at https://karmada.io/partners.
Thanks.
