### ISSUE TITLE
REQUEST: New membership for liangyuanpeng

### ISSUE THREAD

**Issue by liangyuanpeng** [karmada-io/community#62]
### GitHub Username

@liangyuanpeng

### Requirements

- [X] I have reviewed the [community membership guidelines](https://github.com/karmada-io/community/blob/main/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [Karmada mailing list](https://groups.google.com/forum/#!forum/karmada)
- [X] I am actively contributing to 1 or more Karmada subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Karmada GitHub organizations

### Sponsor 1

@RainbowMango

### Sponsor 2

@chaunceyjiang

### List of contributions to the Karmada project

- 30+PRs  https://github.com/karmada-io/karmada/pulls/liangyuanpeng

Next I will focus on exploring how karmada can adapt to cross-cluster stateful applications. Thanks.

**Comment by RainbowMango** [comment]
+1
@liangyuanpeng made great contributions to the community including security improvement, infrastructure maintenance, bugfix and so on.

**Comment by kevin-wangzefeng** [comment]
Invitation sent, you'll be receiving an email shortly. You can also visit https://github.com/karmada-io to accept the invitation.
