### ISSUE TITLE
REQUEST: Organization Chengdu Union Big Data that provides commercial support to Karmada New Commercial Support 

### ISSUE THREAD

**Issue by pandaoknight** [karmada-io/community#64]
### Org or company name

Chengdu Union Big Data Technology Incorporated

### Org or company description

Chengdu Union Big Data Technology Incorporated is a provider of big data and artificial intelligence products and solutions, with a core focus on computer vision technology, multidimensional data analysis and mining technology, and natural language processing technology.

The company focuses on two key areas: "intelligent manufacturing and smart cities". Relying on an "integrated cloud-native digital intelligence service platform", it provides digital intelligence technology services to governments, businesses, and defense units. These services include data governance, data visualization analysis, and data mining for various platforms and scenarios, aiming to help customers reduce costs, improve efficiency, and enhance quality.

### Org or company Website

https://www.unionbigdata.com/

### Org or company logo

![数之联新LOGO-2022_画板 1-01](https://github.com/karmada-io/community/assets/3700872/f117bdf1-eba3-4187-a919-8492c0bfbabb)

### Contact me

shuzhilian@unionbigdata.com

**Comment by RainbowMango** [comment]
Thanks @pandaoknight, Thank you for your support.
We are working on the request, here is a quick update about what we are going to do:
- Building the first page on the Karmada website:  see [the progress in this PR](https://github.com/karmada-io/website/pull/531).
- Getting your organization onto [the Adopter list](https://karmada.io/adopters).
- Publishing your case study on the website.

**Comment by RainbowMango** [comment]
/closed

All tasks have been addressed. Thanks.
The partnership can be found at https://karmada.io/partners.
