### ISSUE TITLE
REQUEST: New membership for a7i

### ISSUE THREAD

**Issue by a7i** [karmada-io/community#68]
### GitHub Username

@a7i

### Requirements

- [X] I have reviewed the [community membership guidelines](https://github.com/karmada-io/community/blob/main/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [Karmada mailing list](https://groups.google.com/forum/#!forum/karmada)
- [X] I am actively contributing to 1 or more Karmada subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Karmada GitHub organizations

### Sponsor 1

@RainbowMango

### Sponsor 2

@XiShanYongYe-Chang

### List of contributions to the Karmada project

- PRs created (15 merged): https://github.com/karmada-io/karmada/pulls?q=is%3Apr+author%3Aa7i+

**Comment by XiShanYongYe-Chang** [comment]
+1 ❤️
@a7i made significant contributions to Karmada.

You still need to find another sponsor who is not from Huawei. (Both me and @XiShanYongYe-Chang are from Huawei).

**Comment by chaunceyjiang** [comment]
+1 ❤️

Thank you for your work～

**Comment by RainbowMango** [comment]
Welcome @a7i !!!
/assign @kevin-wangzefeng

**Comment by kevin-wangzefeng** [comment]
Invitation sent, you'll be receiving an email shortly. You can also visit [@karmada-io](https://github.com/karmada-io) to accept the invitation.

**Comment by a7i** [comment]
Thanks folks! Accepted
