### ISSUE TITLE
REQUEST: New membership for warjiang

### ISSUE THREAD

**Issue by warjiang** [karmada-io/community#70]
### GitHub Username

@warjiang

### Requirements

- [X] I have reviewed the [community membership guidelines](https://github.com/karmada-io/community/blob/main/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [Karmada mailing list](https://groups.google.com/forum/#!forum/karmada)
- [X] I am actively contributing to 1 or more Karmada subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Karmada GitHub organizations

### Sponsor 1

@RainbowMango

### Sponsor 2

@samzong

### List of contributions to the Karmada project

- PRs created (3 merged): https://github.com/karmada-io/karmada/pulls?q=is%3Apr+author%3Awarjiang+is%3Amerged
- Involved with Karmada SIG-UI, make contributions to https://github.com/karmada-io/dashboard continuously

**Comment by RainbowMango** [comment]
+1

**Comment by warjiang** [comment]
@samzong Please help review ~

**Comment by samzong** [comment]
+1 approve

**Comment by RainbowMango** [comment]
/assign @kevin-wangzefeng 

By the way, @warjiang is one of the lead of SIG-UI and made significant contributions to the dashboard. I believe we are going to have an official release soon!

**Comment by kevin-wangzefeng** [comment]
Welcome onboard and looking forward to more of your contribution!
Invitation has been sent, you may visit @karmada-io to accept and join.

**Comment by warjiang** [comment]
Thanks folks! Already accepted 🚀

**Comment by RainbowMango** [comment]
Good!
/close
