### ISSUE TITLE
Adopter Onboarding for Tongcheng Travel

### ISSUE THREAD

**Issue by zhzhuang-zju** [karmada-io/community#75]
Welcome to Karmada Adopters Onboarding!

This is an issue created to help onboard your organization into the [adopters](https://karmada.io/adopters/).

We would like your organization to complete onboarding within one week of acceptance.

Please track your progress by using "Quote reply" to create your own copy of this checklist in an issue, so that you can update the status as you finish items.

**Things that Karmada will need from your organization:**

- [x] Name of your organization or company
- [x] Link to your website
- [x] Your country
- [ ] Your contact info(such as Email, Twitter, WeChat)
- [x] Usage scenario
- [x] Usage stage(evaluating, production)
- [x] Logo(Optional, this will not be used for commercial purposes.) 
- [x] Whether your organization need the help from community

To complete the above information, please leave a comment on the [issue](https://github.com/karmada-io/karmada/issues/4540).

**Things that your organization need do or karmada community will help to do:**

- [ ] Edit the list of adopters in [adopters.md](https://github.com/karmada-io/website/blob/main/src/pages/adopters.md) and open a Pull Request to [karmada-io/website](https://github.com/karmada-io/website).
- [ ] Edit the list of adopters in [adopters.md (Chinese)](https://github.com/karmada-io/website/blob/main/i18n/zh/docusaurus-plugin-content-pages/adopters.md) and open a Pull Request to [karmada-io/website](https://github.com/karmada-io/website).

After completing all of the above tasks, you can see your organization in [adopters](https://karmada.io/adopters/).

Thanks a lot for being part of our community - we very much appreciate it!

**Comment by zhzhuang-zju** [comment]
see https://github.com/karmada-io/karmada/issues/4540#issuecomment-2190886046

**Comment by zhzhuang-zju** [comment]
cc @XiShanYongYe-Chang Can you help with this?

**Comment by XiShanYongYe-Chang** [comment]
> cc @XiShanYongYe-Chang Can you help with this?

Of course.
