### ISSUE TITLE
REQUEST: New membership for affan-7

### ISSUE THREAD

**Issue by Affan-7** [karmada-io/community#80]
### GitHub Username

@affan-7

### Requirements

- [X] I have reviewed the [community membership guidelines](https://github.com/karmada-io/community/blob/main/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [Karmada mailing list](https://groups.google.com/forum/#!forum/karmada)
- [X] I am actively contributing to 1 or more Karmada subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Karmada GitHub organizations

### Sponsor 1

@XiShanYongYe-Chang

### Sponsor 2

@Vacant2333 

### List of contributions to the Karmada project

https://github.com/karmada-io/karmada/pull/5033
https://github.com/karmada-io/karmada/pull/4622
https://github.com/karmada-io/karmada/pull/4514
https://github.com/karmada-io/karmada/pull/4513
https://github.com/karmada-io/karmada/pull/4512
https://github.com/karmada-io/karmada/pull/3906
https://github.com/karmada-io/website/pull/453
https://github.com/karmada-io/website/pull/443
https://github.com/karmada-io/website/pull/441
https://github.com/karmada-io/website/pull/440

**Comment by XiShanYongYe-Chang** [comment]
Hi @Affan-7, sponsors need people from two different companies. You may need to find another person to act as your sponsor.

**Comment by Affan-7** [comment]
@chaosi-zju can you please help me here?

**Comment by XiShanYongYe-Chang** [comment]
Maybe we can ask @Vacant2333's help.

**Comment by Vacant2333** [comment]
@Affan-7 hi, thanks for your contributions, u can assign me as a sponsor for u

**Comment by Affan-7** [comment]
Assigned! Thanks for sponsoring me @Vacant2333.

**Comment by kevin-wangzefeng** [comment]
Thanks for your contributions.
Invitation sent, you can visit https://github.com/karmada-io to accept it.
