### ISSUE TITLE
REQUEST: New membership for seanlaii

### ISSUE THREAD

**Issue by seanlaii** [karmada-io/community#84]
### GitHub Username

@seanlaii

### Requirements

- [X] I have reviewed the [community membership guidelines](https://github.com/karmada-io/community/blob/main/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [Karmada mailing list](https://groups.google.com/forum/#!forum/karmada)
- [X] I am actively contributing to 1 or more Karmada subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Karmada GitHub organizations

### Sponsor 1

@RainbowMango

### Sponsor 2

@whitewindmills

### List of contributions to the Karmada project

- PRs created (9 merged): https://github.com/karmada-io/karmada/pulls?q=is%3Apr+author%3Aseanlaii+

**Comment by RainbowMango** [comment]
+1
Appreciate the contributions made to the community!

**Comment by whitewindmills** [comment]
welcome🎉🎉

**Comment by RainbowMango** [comment]
/assign @kevin-wangzefeng 
for the membership invitation.

**Comment by kevin-wangzefeng** [comment]
Thanks for your contributions, and welcome onboard!
Invitation sent, you can visit https://github.com/karmada-io to accept it.

**Comment by seanlaii** [comment]
Thank you all! I have accepted the invitation. Look forward to contributing more to this project.
