### ISSUE TITLE
REQUEST: New membership for @anujagrawal699

### ISSUE THREAD

**Issue by anujagrawal699** [karmada-io/community#86]
### GitHub Username

@anujagrawal699

### Requirements

- [x] I have reviewed the [community membership guidelines](https://github.com/karmada-io/community/blob/main/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [Karmada mailing list](https://groups.google.com/forum/#!forum/karmada)
- [X] I am actively contributing to 1 or more Karmada subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Karmada GitHub organizations

### Sponsor 1

@zhzhuang-zju

### Sponsor 2

@Vacant2333

### List of contributions to the Karmada project

PRs: https://github.com/karmada-io/karmada/pulls/anujagrawal699
Issues: https://github.com/karmada-io/karmada/issues/created_by/anujagrawal699

* Member for more than 3 months
* 49 PR merged
* Active in Karmada community and attended Karmada biweekly meetings for the same
* Completed LFX mentorship program in 2024
* Contributed significant test coverage improvements to the codebase

**Comment by Vacant2333** [comment]
+1❤️

**Comment by anujagrawal699** [comment]
> Thanks for your contributions and welcome onboard! The invitation has been sent, you may check your email or visit https://github.com/karmada-io to accept it.

Thank you so much!!

**Comment by RainbowMango** [comment]
Welcome @anujagrawal699 !
/close
