### ISSUE TITLE
REQUEST: New membership for @mohamedawnallah

### ISSUE THREAD

**Issue by mohamedawnallah** [karmada-io/community#87]
### GitHub Username

@mohamedawnallah

### Requirements

- [X] I have reviewed the [community membership guidelines](https://github.com/karmada-io/community/blob/main/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [Karmada mailing list](https://groups.google.com/forum/#!forum/karmada)
- [X] I am actively contributing to 1 or more Karmada subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Karmada GitHub organizations

### Sponsor 1

@XiShanYongYe-Chang

### Sponsor 2

@zhzhuang-zju

### Sponsor 3

@chaunceyjiang

### Sponsor 4

@chaosi-zju 

### List of contributions to the Karmada project

- ✅ 80 PRs merged and 28 PRs in review ⏳ - [PRs](https://github.com/karmada-io/karmada/pulls?q=+is%3Apr+author%3Amohamedawnallah+)
- ✅ 6 Issues closed and 6 Issues open ⏳ - [Issues](https://github.com/karmada-io/karmada/issues?q=is%3Aissue+author%3Amohamedawnallah)
- ✅ Completed LFX mentorship @ Karmada Fall 2024 - [Tracking Issue](https://github.com/karmada-io/karmada/issues/5491)

**Comment by zhzhuang-zju** [comment]
+1 ❤️

**Comment by XiShanYongYe-Chang** [comment]
+1 ❤️

Hi, @zhzhuang-zju and I are both form the same company, you need to add a sponsor from another company or organization.

**Comment by mohamedawnallah** [comment]
> Hi, @zhzhuang-zju and I are both form the same company, you need to add a sponsor from another company or organization.

How about @chaosi-zju? They interacted with one of my issues and reviewed the PR I submitted to resolve it 🙏:  
- **Issue**: [karmada-io/karmada#5578](https://github.com/karmada-io/karmada/issues/5578)
- **PR**: [karmada-io/karmada#5593](https://github.com/karmada-io/karmada/pull/5593)

**Comment by zhzhuang-zju** [comment]
Hah, coincidentally, so is he. @chaunceyjiang Would you like to be the sponsor of @mohamedawnallah?

**Comment by chaunceyjiang** [comment]
+1 ❤️❤️❤️

**Comment by RainbowMango** [comment]
I see @mohamedawnallah already accepted it.
Welcome @mohamedawnallah !
/close
