### ISSUE TITLE
REQUEST: New membership for @CharlesQQ

### ISSUE THREAD

**Issue by CharlesQQ** [karmada-io/community#90]
### GitHub Username

@CharlesQQ

### Requirements

- [X] I have reviewed the [community membership guidelines](https://github.com/karmada-io/community/blob/main/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [Karmada mailing list](https://groups.google.com/forum/#!forum/karmada)
- [X] I am actively contributing to 1 or more Karmada subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Karmada GitHub organizations

### Sponsor 1

@XiShanYongYe-Chang

### Sponsor 2

@chaunceyjiang

### List of contributions to the Karmada project

- 16 PRs merged and 7 PRs in review  [PR](https://github.com/karmada-io/karmada/pulls?q=is%3Apr+author%3ACharlesQQ+) 
- 16 Issues closed and 19 Issues open [issue](https://github.com/karmada-io/karmada/issues?q=is%3Aissue+author%3ACharlesQQ)

**Comment by XiShanYongYe-Chang** [comment]
+1
Welcome! 👍

**Comment by RainbowMango** [comment]
Welcome @CharlesQQ !

**Comment by chaunceyjiang** [comment]
+1
❤️❤️❤️

**Comment by RainbowMango** [comment]
Welcome @CharlesQQ, I'm going to close this application as you have accepted the invitation.
/close
